### ISSUE TITLE
At certain angles, in certain positions, using the default profile, you will encounter attacks on yourself when hitting crops or grass.

### ISSUE THREAD

**Issue by TW527E** [Paulem79/AttackThrough#1]
As title

https://github.com/user-attachments/assets/e65d94d6-0ff8-490d-ab05-631d947f51d1

**Comment by Paulem79** [comment]
Okay interesting thanks, I'm trying to fix that

**Comment by Paulem79** [comment]
Should be good ! Thanks for your report
